services:
  controleacademico:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: controle_academico
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: controleacademico_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: controleacademico
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - controleacademico-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  controleacademico-postgres-data:
