spring:
  application:
    name: controle-academico
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME:controleacademico}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
security:
  jwt:
    key:
      private: ${JWT_PRIVATE_KEY_PATH}
      public: ${JWT_PUBLIC_KEY_PATH}
    token:
      access:
        expiry-in-seconds: 3600
      refresh:
        expiry-in-seconds: 10800
    roles-claim-name: roles
