spring:
  application:
    name: controle-academico
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:controleacademico}
    username: ${DB_USERNAME:${POSTGRES_USER:postgres}}
    password: ${DB_PASSWORD:${POSTGRES_PASSWORD:postgres}}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
